version: '3.7'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db

  backend:
    container_name: backend
    build:
      context: ./api
      target: production
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  dbdata:

networks:
  db:
