FROM node:14 as build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

RUN npm prune --production


FROM node:lts-alpine as production

ENV NODE_ENV=production

WORKDIR /app

USER node

COPY --from=build --chown=node:node /app/node_modules /app/node_modules

COPY --from=build --chown=node:node /app/build /app/build

CMD ["node", "build/index.js"]
